//as cartegorias estão organizadas por objeto, quando eu requerir somente todas as musicas é facil de pegar, porem quando eu definir la no meu layout,ele ja vai conter o objeto a musica tlgd
export const cartegories = [
 
//lofi chill
[
    {name : "Chillhop Radio - jazzy & lofi hip hop beats 🐾",
        url : "https://www.youtube.com/watch?v=5yx6BWlEVcY",
        type : "live",authorname : "Chillhop Music"},
        
        {name : "lofi hip hop radio 📚 - beats to relax/study to",
        url : "https://www.youtube.com/watch?v=jfKfPfyJRdk",
        type : "live",authorname : "lofigirl"},
    {name : "BlockBuster 🎥 No Copyright Lofi Hip Hop & Chillhop Mix 2022 | Chill lofi beats to study / relax to",
    url : "https://www.youtube.com/watch?v=BEXL80LS0-I",
    type : "playlist",authorname : "Stomp's Playlist"},
],
//vibes
[
    
    {name : "Aesthetic",
    url : "https://www.youtube.com/watch?v=qELmC7r0RKg",
    type : "music",authorname : "Tollam Kim"},
    {name : "Kylie Vibes",
    url : "https://www.youtube.com/watch?v=7ru0pMwmuWY",
    type : "music",authorname : "Tollam Kim"},
    {name : "Sweet Sunset",
    url : "https://www.youtube.com/watch?v=7XdhxXSzPHU",
    type : "music",authorname : "Tollan Kim & dulai"},
    {name : "Clouds",
    url : "https://www.youtube.com/watch?v=TFeazBaTYVc",
    type : "music",authorname : "Tollam Kim"},
    {name : "Kylie Vibes",
    url : "https://www.youtube.com/watch?v=7XdhxXSzPHU",
    type : "music",authorname : "Tollam Kim"},
    {name : "Hurt - New Jeans (Lofi Remix)",
    url : "https://www.youtube.com/watch?v=6I2pyW6dmsE",
    type : "music",authorname : "Tollam Kim"},
    {name : "And So It Begins [Lo-fi]",
    url : "https://youtu.be/BH-SnQ8J1VU?si=ropXNpyTN978V9NC",
    type : "music",authorname : "BreakingCopyright"},
    
    {name : "You inspire me ◍ lofi ◍ music for stress relief",
    url : "https://www.youtube.com/watch?v=gRmxPMQzPKc",
    type : "playlist",authorname : "Dreamy"}
    
],
//undertale
[
    {name : "001 - Once Upon A Time | Undertale OST",
    url : "https://youtu.be/s7RRgF5Ve_E?si=yVNBCREUAU0VmtJT",
    type : "music",authorname : "Toby Fox"},
  /*  {name : "| Undertale OST",
    url : "",
    type : "music",authorname : "Toby Fox"},
    {name : "| Undertale OST",
    url : "",
    type : "music",authorname : "Toby Fox"},
    {name : "| Undertale OST",
    url : "",
    type : "music",authorname : "Toby Fox"},
    {name : "| Undertale OST",
    url : "",
    type : "music",authorname : "Toby Fox"},
    {name : "| Undertale OST",
    url : "",
    type : "music",authorname : "Toby Fox"},
    {name : "| Undertale OST",
    url : "",
    type : "music",authorname : "Toby Fox"}
*/],
//minecraft
[
    {name : "Minecraft Music Slowed Down 🎵 With Rain 🌧️",
    url : "https://www.youtube.com/watch?v=vZeWxNnL8bc",
    type : "playlist",authorname : "IAmZacke"},
    {name : "03 Subwoofer Lullaby  | SURVIVAL MINECRAFT",
    url : "https://youtu.be/Gpd85y_iTxY?si=YKRAJgtNgGHx0v9G",
    type : "music",authorname : "C418"},
    {name : "05 Living Mice | SURVIVAL MINECRAFT",
    url : "https://youtu.be/oGxQNQtnr6Q?si=H-XlMTDa6LdGjf-r",
    type : "music",authorname : "C418"},
    {name : "07 Haggstrom | SURVIVAL MINECRAFT",
    url : "https://youtu.be/laZusNy8QiY?si=ttq-_o1356tVXiXH",
    type : "music",authorname : "C418"},
    {name : "08 Minecraft | SURVIVAL MINECRAFT",
    url : "https://youtu.be/qq-RGFyaq0U?si=yPlkMjP4KAkv51hb",
    type : "music",authorname : "C418"},
    {name : "11 Mice on Venus | SURVIVAL MINECRAFT",
    url : "https://youtu.be/DZ47H84Bc_Q?si=zNFiDI1KQzvQ6VLo",
    type : "music",authorname : "C418"},
    {name : "12 Dry Hands | SURVIVAL MINECRAFT",
    url : "https://youtu.be/4i0d6CPLSGo?si=rfGmPCVuJPq6ni4c",
    type : "music",authorname : "C418"},
    {name : "13 Wet Hands | SURVIVAL MINECRAFT",
    url : "https://youtu.be/mukiMaOSLEs?si=hCBiQSE3MgjpWFCM",
    type : "music",authorname : "C418"},
    {name : "14 Clark | SURVIVAL MINECRAFT",
    url : "https://youtu.be/UhWjWdlnmEw?si=KBPn-dhoQ6vpb-Tn",
    type : "music",authorname : "C418"},
    {name : "18 Sweden | SURVIVAL MINECRAFT",
    url : "https://youtu.be/aBkTkxKDduc?si=o2sbR0RLz8daK45n",
    type : "music",authorname : "C418"},
    {name : "21 Danny | SURVIVAL MINECRAFT",
    url : "https://youtu.be/SznnVAnkv3c?si=mb5W6E1zrfLenTms",
    type : "music",authorname : "C418"},
    {name : "08 Biome Fest | CREATIVE MINECRAFT",
    url : "https://youtu.be/8sglGXAfHLc?si=ZUcc6JIehou1ogRh",
    type : "music",authorname : "C418"},
    {name : "04 Blind Spots | CREATIVE MINECRAFT",
    url : "https://youtu.be/77Fv8gtZyuA?si=52DbBQ1W2vafj8xj",
    type : "music",authorname : "C418"},
    {name : "10 Haunt Muskie | CREATIVE MINECRAFT",
    url : "https://youtu.be/ao8U6D_F3dE?si=OjTkNdXMN8sJAmot",
    type : "music",authorname : "C418"},
    {name : "18 Dreiton | CREATIVE MINECRAFT",
    url : "https://youtu.be/rbIGUF9QmXg?si=1A1MVKuZ0RLhBnS3",
    type : "music",authorname : "C418"},
    {name : "13 Aria Math | CREATIVE MINECRAFT",
    url : "https://youtu.be/atgjKEgSqSU?si=bznX2LdZD_eqCWGx",
    type : "music",authorname : "C418"}
    ,
    {name : "16 Taswell | CREATIVE MINECRAFT",
    url : "https://youtu.be/Mj6jF7I2s10?si=SDRSbgeA_wQcqsGc",
    type : "music",authorname : "C418"},
],
//omori
[
    {name : "OMORI Songs To Help You Sleep/Relax/Cry? (OST Playlist)",
    url : "https://www.youtube.com/watch?v=pw-2e3T03Co",
    type : "playlist",authorname : "peng weng"},

    {name : "OMORI - lofi/chill mix",
    url : "https://www.youtube.com/watch?v=az3qYjAnPB4",
    type : "playlist",authorname : "Lavos"},

    {name : "005 By Your Side.",
    url : "https://youtu.be/7GIWV__qx4M?si=FGcpwWH0gOo72mmN",
    type : "music",authorname : "OMOCAT"},
    {name : "006 Let's Get Together Now!",
    url : "https://youtu.be/GoWgI1V_WDA?si=gXU9qk35q2nWxgIB",
    type : "music",authorname : "OMOCAT"},
    {name : "025 Lovesick - 80,000 Lightyears",
    url : "https://youtu.be/YiDYHPHm6Rg?si=ZmygSNKGJKJepjug",
    type : "music",authorname : "OMOCAT"},
    {name : "088 Lost Library",
    url : "https://youtu.be/31jhk_A3mYk?si=PGOCZptJddpiaKYw",
    type : "music",authorname : "OMOCAT"},
    {name : "158 A Home For Flowers (Daisy)",
    url : "https://youtu.be/9n6pcfsA3Yo?si=R8ngeddlWEzj8TKl",
    type : "music",authorname : "OMOCAT"},
    {name : "172 DUET",
    url : "https://youtu.be/ACon4txJiDA?si=_P1yEFh5Zrb7BaUx",
    type : "music",authorname : "OMOCAT"},
    {name : "096 WHITE SPACE",
    url : "https://youtu.be/t815nBXavpE?si=g9eFsPyE7jkZGXs0",
    type : "music",authorname : "OMOCAT"},
]
]
  

//cartegories.get values (pega os objetos)